apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorten-service
  labels:
    app: shorten-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shorten-service
  template:
    metadata:
      labels:
        app: shorten-service
    spec:
      containers:
      - name: shorten-service
        image: shorten-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3000"
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres:5432/shorty"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: shorten-service
spec:
  selector:
    app: shorten-service
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP 